import pptxgen from "pptxgenjs";
import * as XLSX from "xlsx";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { saveAs } from "file-saver";

export async function exportToPPT(title: string, content: string) {
  const pres = new pptxgen();
  
  // Title Slide
  const slide = pres.addSlide();
  slide.addText(title, { x: 1, y: 2, w: '80%', h: 1, fontSize: 36, bold: true, color: '003366', align: 'center' });
  slide.addText("Generated by BharatMind AI", { x: 1, y: 3, w: '80%', h: 1, fontSize: 18, color: '666666', align: 'center' });

  // Split content into sections based on markdown headings
  const sections = content.split(/(?=^#{1,3} )/m).filter(Boolean);
  
  for (const section of sections) {
    const lines = section.trim().split('\n');
    let slideTitle = "Overview";
    let slideContent = section;

    if (lines[0].startsWith('#')) {
      slideTitle = lines[0].replace(/^#+\s*/, '').substring(0, 50);
      slideContent = lines.slice(1).join('\n').trim();
    }

    if (!slideContent) continue;

    // Truncate content to fit on a slide (naive approach)
    if (slideContent.length > 800) {
      slideContent = slideContent.substring(0, 797) + '...';
    }

    const s = pres.addSlide();
    s.addText(slideTitle, { x: 0.5, y: 0.5, w: '90%', h: 0.5, fontSize: 24, bold: true, color: '003366' });
    s.addText(slideContent, { x: 0.5, y: 1.2, w: '90%', h: 4, fontSize: 14, color: '333333', valign: 'top' });
  }

  await pres.writeFile({ fileName: `${title}.pptx` });
}

export async function exportToExcel(title: string, content: string) {
  const wb = XLSX.utils.book_new();
  
  // Create a summary sheet
  const wsData = [
    ["BharatMind AI Financial & Strategy Report"],
    ["Generated on", new Date().toLocaleDateString()],
    [],
    ["Section", "Content"]
  ];
  
  const sections = content.split(/(?=^#{1,3} )/m).filter(Boolean);
  for (const section of sections) {
    const lines = section.trim().split('\n');
    let sectionTitle = "Overview";
    let sectionContent = section;

    if (lines[0].startsWith('#')) {
      sectionTitle = lines[0].replace(/^#+\s*/, '');
      sectionContent = lines.slice(1).join('\n').trim();
    }
    
    wsData.push([sectionTitle, sectionContent.substring(0, 30000)]); // Excel cell limit is ~32k chars
  }
  
  const ws = XLSX.utils.aoa_to_sheet(wsData);
  
  // Auto-size columns
  ws['!cols'] = [{ wch: 30 }, { wch: 100 }];
  
  XLSX.utils.book_append_sheet(wb, ws, "Analysis");

  XLSX.writeFile(wb, `${title}.xlsx`);
}

export async function exportToWord(title: string, content: string) {
  const paragraphs = content.split('\n').map(line => {
    if (line.startsWith('# ')) {
      return new Paragraph({ text: line.replace('# ', ''), heading: HeadingLevel.HEADING_1 });
    } else if (line.startsWith('## ')) {
      return new Paragraph({ text: line.replace('## ', ''), heading: HeadingLevel.HEADING_2 });
    } else if (line.startsWith('### ')) {
      return new Paragraph({ text: line.replace('### ', ''), heading: HeadingLevel.HEADING_3 });
    } else if (line.trim() === '') {
      return new Paragraph({ text: "" });
    } else {
      return new Paragraph({ children: [new TextRun(line)] });
    }
  });

  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({ text: title, heading: HeadingLevel.TITLE }),
        new Paragraph({ text: "Generated by BharatMind AI", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: "" }),
        ...paragraphs
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${title}.docx`);
}
